export const words = [
    "abril", "agua", "aire", "alas", "alma", "amor", "ángel", "animal", "anillo", "antiguo",
    "aprender", "arte", "avión", "azul", "bailar", "boca", "bosque", "brazo", "calle", "cama",
    "campo", "canción", "carro", "casa", "cielo", "clase", "color", "comida", "corazón", "cuerpo",
    "danza", "diente", "dolor", "dulce", "edad", "energía", "escuela", "espacio", "estrella",
    "familia", "fuego", "fuerza", "gato", "guitarra", "hoja", "invierno", "jardín", "juego", "lago",
    "luz", "mano", "mar", "mirada", "música", "nieve", "nube", "noche", "ojo", "ola", "pájaro", "palabra",
    "paso", "pelota", "pensamiento", "pie", "piedra", "pintura", "poesía", "río", "sangre", "sueño",
    "sol", "sombra", "sonrisa", "sueño", "tarde", "tiempo", "trabajo", "universo", "viento", "vida", "Manzana", "Perro", "Gato", "Casa", "Coche", "Flor", "Sol", "Luna", "Mar", "Montaña",
    "Río", "Árbol", "Libro", "Pelota", "Niño", "Niña", "Hombre", "Mujer", "Amigo", "Amiga",
    "Padre", "Madre", "Hermano", "Hermana", "Abuelo", "Abuela", "Tío", "Tía", "Primo", "Prima",
    "Vecino", "Vecina", "Profesor", "Profesora", "Estudiante", "Escuela", "Universidad", "Trabajo", "Dinero", "Comida", "Bebida",
    "Cena", "Desayuno", "Almuerzo", "Viaje", "Vacaciones", "Tiempo", "Reloj", "Computadora", "Teléfono", "Internet",
    "Película", "Música", "Arte", "Pintura", "Escultura", "Canción", "Bailarín", "Bailarina", "Actor", "Actriz",
    "Director", "Directora", "Peluquero", "Peluquera", "Médico", "Enfermero", "Enfermera", "Hospital", "Medicina", "Enfermedad",
    "Accidente", "Policía", "Ladrón", "Juez", "Abogado", "Juicio", "Testigo", "Prisión", "Escritor", "Escritora",
    "Poeta", "Poesía", "Novela", "Cuento", "Periodista", "Noticia", "Revista", "Peluche", "Jugador", "Juegos",
    "Jugadora", "Deporte", "Baloncesto", "Fútbol", "Tenis", "Nadador", "Nadadora", "Buceo", "Ciclismo", "Aire",
    "Agua", "Fuego", "Tierra", "Viento", "Lluvia", "Nieve", "Rayo", "Trueno", "Arcoíris", "Cielo",
    "Estrella", "Planeta", "Astronauta", "Universo", "Galaxia", "Cometa", "Satélite", "Cámara", "Fotografía", "Video",
    "Grabación", "Película", "Escenario", "Público", "Actor", "Actriz", "Drama", "Comedia", "Tragedia", "Romance",
    "Misterio", "Aventura", "Ciencia ficción", "Fantasía", "Historia", "Geografía", "Matemáticas", "Ciencia", "Química", "Física",
    "Biología", "Botánica", "Zoología", "Animal", "Planta", "Insecto", "Pájaro", "Pez", "Reptil", "Anfibio",
    "Mamífero", "Dinosaurio", "Elefante", "León", "Tigre", "Cebra", "Jirafa", "Oso", "Conejo", "Serpiente",
    "Tortuga", "Rana", "Ballena", "Tiburón", "Delfín", "Caballo", "Vaca", "Oveja", "Cabra", "Cerdo",
    "Pollo", "Pato", "Ganso", "Huevo", "Leche", "Carne", "Pan", "Queso", "Fruta", "Verdura", "Cereales",
    "Arroz", "Pasta", "Sopa", "Ensalada", "Sándwich", "Pizza", "Hamburguesa", "Papas", "Maíz", "Chocolate",
    "Helado", "Pastel", "Dulces", "Sal", "Azúcar", "Aceite", "Vinagre", "Salsa", "Ketchup", "Mostaza",
    "Mayonesa", "Yogur", "Lechuga", "Tomate", "Pepino", "Zanahoria", "Pimiento", "Patata", "Cebolla", "Ajo",
    "Fresa", "Manzana", "Uva", "Plátano", "Naranja", "Limón", "Pera", "Durazno", "Cereza", "Sandía",
    "Melón", "Kiwi", "Frambuesa", "Moras", "Piña", "Coco", "Mango", "Papaya", "Guayaba", "Mora",
    "Pavo", "Cordero", "Pato", "Conejo", "Cerdo", "Pollo", "Ternera", "Avestruz", "Canguro", "Lobo",
    "Zorro", "Búho", "Águila", "Gaviota", "Cuervo", "Paloma", "Colibrí", "Cisne", "Tortuga", "Cocodrilo",
    "Rana", "Salamandra", "Mariposa", "Abeja", "Mosca", "Araña", "Escorpión", "Mosquito", "Pulga", "Hormiga",
    "Langosta", "Cigarra", "Grillo", "Rata", "Ratón", "Ardilla", "Castor", "Nutria", "Murciélago", "Delfín",
    "Ballena", "Tiburón", "Tiburo", "Pez", "Salmón", "Trucha", "Atún", "Carpa", "Sardina", "Anchoa",
    "Langosta", "Cangrejo", "Almeja", "Ostra", "Mejillón", "Pulpo", "Calamar", "Corales", "Medusa", "Atún",
    "Salmón", "Trucha", "Bacalao", "Lubina", "Sardina", "Anchoa", "Langosta", "Cangrejo", "Camarón", "Almeja",
    "Ostra", "Mejillón", "Pulpo", "Calamar",  "Atún", "Salmón", "Trucha", "Bacalao", "Lubina",
    "Sardina", "Anchoa", "Merluza", "Langosta", "Cangrejo", "Camarón", "Gambas", "Almejas", "Ostras", "Mejillones",
    "Pulpos", "Calamares", "Estrellas de mar", "Erizos de mar", "Pepinos de mar", "Corales", "Medusas", "Esponjas de mar", "Atunes", "Salmón", "Truchas", "Bacalaos", "Lubinas", "Sardinas",
    "Anchoas", "Merluzas", "Boquerones", "Alcachofa", "Alcoba", "Alfombra", "Almohada", "Almohadón", "Almuerzo",  "Alquiler",
    "Altavoz", "Ambiente", "Amor", "Amortiguador", "Amuleto", "Anécdota", "Angustia", "Animal", "Anteojos", "Apetito",
    "Apellido", "Apetito", "Apodo", "Aplauso", "Apoyo", "Apunte", "Aprendiz", "Aprendizaje", "Aro", "Arruga",
    "Asiento", "Asombro", "Atención", "Aula", "Aventura", "Aviso", "Baile", "Balcón", "Barco", "Barra",
    "Barril", "Bastón", "Bebé", "Bebida", "Belleza", "Beso", "Bicicleta", "Bienestar", "Billete", "Bolso",
    "Bombero", "Borrador", "Botella", "Botón", "Brillo", "Brote", "Bufanda", "Bulto", "Cabello", "Cabra",
    "Caja", "Cama", "Cámara", "Camarero", "Camino", "Candelabro", "Canguro", "Capucha", "Capullo", "Cara",
    "Caracol", "Carcaj", "Carnaval", "Carta", "Cartera", "Casa", "Cascada", "Casco", "Castigo", "Castillo",
    "Catedral", "Caza", "Cazador", "Celda", "Ceniza", "Cerveza", "Cielo", "Cigarrillo", "Cima", "Cine",
    "Cinturón", "Circo", "Ciudad", "Clase", "Clima", "Club", "Coche", "Cocina", "Comedia", "Cometa",
    "Comida", "Compañero", "Comunicación", "Computadora", "Confianza", "Confort", "Congreso", "Conquista", "Corazón", "Correo",
    "Correr", "Corriente", "Corrupción", "Cosecha", "Cosmético", "Cuchillo", "Cuento", "Cuerda", "Cuerno", "Cuidado",
    "Cultura", "Curiosidad", "Dama", "Danza", "Dardo", "Deber", "Decoración", "Dedo", "Defensa", "Deporte",
    "Desayuno", "Descanso", "Desfile", "Destino", "Dibujo", "Diente", "Dificultad", "Dinero", "Diploma", "Disco",
    "Diseño", "Disfraz", "Diversión", "Doctor", "Documento", "Dolor", "Duda", "Edificio", "Educación", "Efecto",
    "Ejercicio", "Ejemplo", "Elección", "Elevador", "Emoción", "Encanto", "Enfermedad", "Enfrentamiento", "Enigma", "Enlace",
    "Enseñanza", "Entusiasmo", "Equipo", "Escalera", "Escalofrío", "Escándalo", "Escaparate", "Escenario", "Esfuerzo", "Espacio",
    "Espada", "Espectáculo", "Esperanza", "Espejo", "Esquina", "Estación", "Estado", "Estilo", "Estómago", "Estrella",
    "Estudiante", "Éxito", "Examen", "Excursión", "Experiencia", "Exposición", "Extraño", "Familia", "Fantasía", "Faro",
    "Fábrica", "Fiesta", "Fuego", "Flor", "Fondo", "Forma", "Fotografía", "Fruta", "Fuerza", "Futuro",
    "Galería", "Garaje", "Garganta", "Gato", "Generación", "Globo", "Golpe", "Gota", "Granja", "Grano",
    "Grito", "Guardián", "Guitarra", "Hambre", "Hermano", "Herramienta", "Héroe", "Hierba", "Hielo", "Historia",
    "Hombro", "Hoja", "Hogar", "Hombre", "Horizonte", "Huevo", "Idea", "Identidad", "Imágen", "Imaginación",
    "Imperio", "Impresión", "Infierno", "Inflación", "Insecto", "Instinto", "Intelecto", "Intención", "Interior", "Jardín",
    "Jefe", "Jirafa", "Juego", "Jugador", "Jugadora", "Juicio", "Lágrima", "Lago", "Lámpara", "Lanzamiento",
    "Largo", "Lección", "Leche", "Lengua", "Lente", "Límite", "Limpieza", "Llave", "Lluvia", "Lobo",
    "Logro", "Luz", "Maestro", "Maestra", "Maleta", "Malvavisco", "Mamá", "Manta", "Mapa", "Mar",
    "Margarita", "Máquina", "Máscara", "Matemáticas", "Materia", "Mecedora", "Medicina", "Medio", "Melodía", "Memoria",
    "Mente", "Menú", "Mercado", "Merienda", "Mesa", "Miedo", "Miel", "Mimo", "Mina", "Minuto",
    "Mirada", "Misión", "Mochila", "Moda", "Momento", "Montaña", "Mordida", "Movimiento", "Mundo", "Música",
    "Nación", "Nada", "Nacimiento", "Naturaleza", "Nave", "Navegación", "Nido", "Niñez", "Niño", "Noche",
    "Nube", "Número", "Objeto", "Oferta", "Oficina", "Ojo", "Óleo", "Onda", "Oración", "Orden",
    "Origen", "Oro", "Orquesta", "Oscuridad", "Otoño", "Pájaro", "Palabra", "Palacio", "Palma", "Pantalla",
    "Pánico", "Papel", "Par", "Paraguas", "Pared", "Paseo", "Pasión", "Pasillo", "Pasión", "Pastel",
    "Pájaro", "Pecado", "Pelea", "Pelo", "Pena", "Pensamiento", "Pequeño", "Perdón", "Perfume", "Pescado",
    "Pie", "Piel", "Pies", "Pijama", "Pila", "Pintura", "Piso", "Pista", "Placer", "Plan",
    "Planeta", "Plata", "Pluma", "Pobreza", "Poder", "Póker", "Policía", "Política", "Pregunta", "Prensa",
    "Presión", "Primavera", "Princesa", "Prisión", "Problema", "Profesor", "Promesa", "Prueba", "Pueblo", "Puente",
    "Puesta de sol", "Pulgada", "Pulmón", "Punto", "Puñal", "Puñetazo", "Química", "Radio", "Rama", "Ratón",
    "Rayo", "Razón", "Recuerdo", "Red", "Regalo", "Regla", "Relámpago", "Reloj", "Respeto", "Restaurante",
    "Resultado", "Revista", "Risa", "Río", "Riqueza", "Risa", "Roca", "Rodeo", "Ruido", "Sabor",
    "Sal", "Salida", "Salto", "Salvavidas", "Sábado", "Sábana", "Secretario", "Secreto", "Seda", "Sello",
    "Semana", "Sendero", "Silla", "Sirena", "Sonrisa", "Sueño", "Suerte", "Tamaño", "Tapa", "Tarea",
    "Teatro", "Tecnología", "Tela", "Televisión", "Tema", "Tiempo", "Tienda", "Tinta", "Tío", "Tocino",
    "Tren", "Tristeza", "Trofeo", "Tumba", "Unidad", "Universidad", "Uso", "Vehículo", "Vela", "Venganza",
    "Ventana", "Verano", "Verbo", "Verdadero", "Vestido", "Vida", "Viaje", "Viento", "Vino", "Violín",
    "Visión", "Vuelo", "Zanahoria", "Zapato", "Zoológico", "Abrazo", "Aburrimiento", "Accidente", "Aceite", "Acuerdo", "Adiós", "Agua", "Alegría", "Amistad", "Amor", "Angustia", "Aplauso", "Arco iris", "Atardecer", "Aventura", "Baile", "Belleza", "Beso", "Boda", "Canto", "Carcajada", "Caricia", "Cine", "Comida", "Compromiso", "Confusión", "Corazón", "Cumpleaños", "Danza", "Deseo", "Dolor", "Emoción", "Encuentro", "Enfado", "Esperanza", "Felicidad", "Fiesta", "Ilusión", "Lágrima", "Libertad", "Luna", "Magia", "Mañana", "Melodía", "Mirada", "Momento", "Muerte", "Música", "Noche", "Pasión", "Pintura", "Placer", "Recuerdo", "Risas", "Sol", "Sueño"
  ];
  